In [3]:
# two types of data structures
# data frames
import pandas as pd
df = pd.DataFrame({
    "cgpa":[9.0, 9.8, 9.1],
    "Name":["kirti", "tanya", "sahil"]
})

In [4]:
df

   cgpa   Name
0   9.0  kirti
1   9.8  tanya
2   9.1  sahil

In [22]:
# vectorized operation on series
s1 = pd.Series([5,6,7])
s2 = pd.Series([9, 10, 4])
print(s1+s2)

0    14
1    16
2    11
dtype: int64

In [5]:
# data frames in pandas and operations
import pandas as pd
info = {
    "CGPA":[9.8, 9.0, 9.7],
    "Grade":["A", "C", "B"],
    "Name":["Adam", "Bob", "Charlie"]
}

df = pd.DataFrame(info)
print(df)
print(df.index)
print(df.columns)
print(type(df))

   CGPA Grade     Name
0   9.8     A     Adam
1   9.0     C      Bob
2   9.7     B  Charlie
RangeIndex(start=0, stop=3, step=1)
Index(['CGPA', 'Grade', 'Name'], dtype='object')
<class 'pandas.core.frame.DataFrame'>

In [14]:
# creating data frame using numpy array
import numpy as np;
arr = np.array([[9.8, 9.0, 9.7], ["A", "C", "B"], ["Adam", "Bob", "Charlie"]])
arr = pd.DataFrame(arr, columns=["CGPA", "Grade", "Name"])
print(arr)

   CGPA Grade     Name
0   9.8   9.0      9.7
1     A     C        B
2  Adam   Bob  Charlie

In [29]:
# reading data from csv files
data = pd.read_csv("data.csv")
# print(data)

# data viewing and inspection
# function or methods
data.head() #returns first 5 rows by default we can also explicitely pass the row count
data.tail() #returns last 5 rows by default we can also explicitely pass the row count
data.sample() #shows randome rows we can pass explicitly the count
data.info() # return column names, data types and memory usage 
data.describe() #show descriptive statistics for numeric values
data.nunique() #shows count or unique value in each columns

# we also have attributes
data.shape
data.dtypes
data.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      31 non-null     object
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB

Index(['Duration', 'Date', 'Pulse', 'Maxpulse', 'Calories'], dtype='object')

In [61]:
# indexing and data selection
data["Date"] #return a series
data[["Pulse", "Maxpulse"]] #return a data frame

# selecting rows by labels
data.loc[0] #1st row by label
data.loc[0:3] #row 0 to 3 both inclusive in loc
data.loc[0,"Pulse"] #0th row with particular columns

#selecting rows by index
data.iloc[0] # first row
data.iloc[0:6] # 6th row is non inclusive
data.iloc[0, 3] #1st row and third column

# selecting single cell
data.at[0, "Pulse"]
data.iat[0, 2]

data[data["Pulse"] > 110]
data[(data["Pulse"] > 100) & (data["Calories"] < 200)]
data[(data["Pulse"] > 20) | (data["Calories"] < 70)]

# Query method
data.query("Duration >= 60 and Maxpulse > 100")
mycalories = 195.1
data.query("Calories == @mycalories")

   Duration          Date  Pulse  Maxpulse  Calories
8        30  '2020/12/09'    109       133     195.1

In [5]:
import pandas as pd
data = pd.read_csv("data.csv")
# handling missing values 
data.isnull()
data.isnull().sum()
data.fillna(0)
data.ffill()
data.bfill()
# data.dropna() drop rows with null values

# handling duplicates value
data.duplicated()
# data.drop_duplicates() remove rows with duplicates value

# print(data.duplicated("Maxpulse"))
# print(data.duplicated(["Maxpulse", "Pulse"]))

# changing data type
# data["Calories"] = data["Calories"].astype(int) 

# datetime object -> convert string , number , array to date time object 
str = "2026-1-24"
date = pd.to_datetime(str)
date

# string cleaning
str1 = "introduction"
str2 = "   Free time"
str3 = "BEST FRIEND"
str4 = "one super power"
str5 = "favourite food"

str3.lower()
str1.upper()
str4.capitalize()
str2.strip()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
13    False
14    False
15    False
16    False
17     True
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26     True
27    False
28    False
29    False
30    False
31    False
dtype: bool

'Free time'

In [6]:
# reading data from csv file to perform our string operation on real world data
df = pd.read_csv("netflix_titles.csv")
df.describe()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [7]:
df.head(30)
df["type"].str.lower()
df["country"].str.upper()
print(df["title"].str.split(""))
type(df["title"].str.split("")[0])
df["country"].str.contains("India")
df["country"].str.contains("India", case=False)

0       [, D, i, c, k,  , J, o, h, n, s, o, n,  , I, s...
1             [, B, l, o, o, d,  , &,  , W, a, t, e, r, ]
2                         [, G, a, n, g, l, a, n, d, s, ]
3       [, J, a, i, l, b, i, r, d, s,  , N, e, w,  , O...
4                [, K, o, t, a,  , F, a, c, t, o, r, y, ]
                              ...
8802                               [, Z, o, d, i, a, c, ]
8803                [, Z, o, m, b, i, e,  , D, u, m, b, ]
8804                   [, Z, o, m, b, i, e, l, a, n, d, ]
8805                                     [, Z, o, o, m, ]
8806                               [, Z, u, b, a, a, n, ]
Name: title, Length: 8807, dtype: object

In [97]:
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [33]:
# transforming the data
import pandas as pd
data = pd.read_csv("data.csv")
df = pd.read_csv("netflix_titles.csv")
# assign - creates a new columns or modify existing column
data = data.assign(age = 60)
data

# apply function takes a function as input and thats why this is called higher order
data["age"].apply(lambda x : x+10) # increment x value by 10
data["age_m_20"] = data["age"].apply(lambda x: x-20) #can 
data

# map() is used to transform values of a Series using a dictionary or function. Unmatched value replace with nan
df["country"].map({"United States": "US", "India":"IN", "South Africa":"SA"})

# replace Works on Series and DataFrame Replaces only matched values Unmatched values stay unchanged
df.replace({"90 min": "80 min"}) #duration 

df.sort_values("release_year", ascending=False)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
372,s373,Movie,Rurouni Kenshin: The Beginning,Keishi Otomo,"Takeru Satoh, Kasumi Arimura, Issey Takahashi,...",NaN,"July 30, 2021",2021,TV-MA,138 min,"Action & Adventure, International Movies","Before he was a protector, Kenshin was a fears..."
74,s75,TV Show,The World's Most Amazing Vacation Rentals,NaN,NaN,NaN,"September 14, 2021",2021,TV-PG,2 Seasons,Reality TV,"With an eye for every budget, three travelers ..."
373,s374,Movie,The Last Mercenary,David Charhon,"Jean-Claude Van Damme, Alban Ivanov, Éric Judo...",NaN,"July 30, 2021",2021,TV-MA,112 min,"Action & Adventure, Comedies, International Mo...",A legendary secret agent-turned-mercenary come...
375,s376,Movie,Resort to Love,Steven Tsuchida,"Christina Milian, Jay Pharoah, Sinqua Walls, T...",NaN,"July 29, 2021",2021,TV-14,102 min,"Comedies, Romantic Movies",Reeling from a broken heart and career meltdow...
...,...,...,...,...,...,...,...,...,...,...,...,...
8763,s8764,Movie,WWII: Report from the Aleutians,John Huston,NaN,United States,"March 31, 2017",1943,TV-PG,45 min,Documentaries,Filmmaker John Huston narrates this Oscar-nomi...
8739,s8740,Movie,Why We Fight: The Battle of Russia,"Frank Capra, Anatole Litvak",NaN,United States,"March 31, 2017",1943,TV-PG,82 min,Documentaries,This installment of Frank Capra's acclaimed do...
7790,s7791,Movie,Prelude to War,Frank Capra,NaN,United States,"March 31, 2017",1942,TV-14,52 min,"Classic Movies, Documentaries",Frank Capra's documentary chronicles the rise ...
8205,s8206,Movie,The Battle of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,"March 31, 2017",1942,TV-14,18 min,"Classic Movies, Documentaries",Director John Ford captures combat footage of ...
4250,s4251,TV Show,Pioneers: First Women Filmmakers*,NaN,NaN,NaN,"December 30, 2018",1925,TV-14,1 Season,TV Shows,This collection restores films from women who ...

In [31]:
# renaming and reordering data frames
df = pd.DataFrame({
    "A":[1,2,3],
    "B":[4,5,6],
    "C":[7,8,9]
})

renamed_df = df.rename(columns={"A":"X", "B":"Y", "C":"Z"})
renamed_df

   X  Y  Z
0  1  4  7
1  2  5  8
2  3  6  9

In [44]:
# group by and aggregate function
raw_data = pd.read_csv("raw_data.csv")
# we use group by function to split data into multiple groups so that we can apply some aggregation functions
# for example if we want mean salary based on country 
raw_data.groupby("country")["income"].mean()

# similarily based on male and female 
raw_data.groupby("gender")["income"].mean()

# if we want to apply multiple aggregation like min, max, count, sum together we can use agg
raw_data.groupby("country")["income"].agg(["mean", "max", "min"])

# we can also rename them 
raw_data.groupby("country")["income"].agg(mean_salary="mean", max_salary="max", min_salary="min")

# aggregation on multiple columns 
raw_data.groupby("country").agg(
    avg_income=("income","mean"), 
    ave_age=("age","mean")
)

         avg_income  ave_age
country
Canada      62000.0      NaN
China       51000.0     27.0
India       73000.0     45.0
Mexico      45000.0      NaN
Spain           NaN     34.0
USA         55400.0     29.5

In [8]:
# reshaping methods 
# melt convert wide data into long data
import pandas as pd;
df = pd.DataFrame({
    "country":["USA", "India", "Canada", "China"],
    "year":[2021, 2022, 2026, 2025],
    "sales":[100, 120, 90, 110],
    "profit":[22, 23, 24, 25],
})

melted_df = df.melt(
    id_vars=["country","year"],
    value_vars=["sales", "profit"],
    var_name="metrics",
    value_name="value"
)

melted_df

# pivot - convert long format into wide format
original_data = melted_df.pivot(
    index = ["country", "year"],
    columns = "metrics",
    values = "value"
)

original_data

metrics       profit  sales
country year
Canada  2026      24     90
China   2025      25    110
India   2022      23    120
USA     2021      22    100

In [4]:
melted_df

  country  year metrics  value
0     USA  2021   sales    100
1   India  2022   sales    120
2  Canada  2026   sales     90
3   China  2025   sales    110
4     USA  2021  profit     22
5   India  2022  profit     23
6  Canada  2026  profit     24
7   China  2025  profit     25

In [49]:
df

  country  year  sales  profit
0     USA  2021    100      22
1   India  2022    120      23
2  Canada  2026     90      24
3   China  2025    110      25

In [16]:
# combining and joining methods
df_customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "name": ["Adam", "Bob", "Charlie", "Dave"]
})

df_orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104],
    "customer_id": [2, 1, 4, 5],
    "amount": [250, 120, 300, 180]
})

pd.merge(df_customers, df_orders, on="customer_id") #innner joins (join only common values
pd.merge(df_customers, df_orders, on="customer_id" , how="left") #keep common plus whole left data
pd.merge(df_customers, df_orders, on="customer_id", how="right") #keep common plus right data
pd.merge(df_customers, df_orders, on="customer_id", how="outer") #keep both data whole

   customer_id     name  order_id  amount
0            1     Adam     102.0   120.0
1            2      Bob     101.0   250.0
2            3  Charlie       NaN     NaN
3            4     Dave     103.0   300.0
4            5      NaN     104.0   180.0

In [11]:
df_customers

   customer_id     name
0            1     Adam
1            2      Bob
2            3  Charlie
3            4     Dave

In [12]:
df_orders

   order_id  customer_id  amount
0       101            2     250
1       102            1     120
2       103            4     300
3       104            5     180

In [20]:
# concat -> used to concat 2 data frames either vertically or horizont
df1 = pd.DataFrame({
    "id":[1,2,3],
    "Name":["tanya", "sahil", "kirti"]
})

df2 = pd.DataFrame({
    "id":[4,5,6],
    "Name":["Shradha didi", "Aman Bhaiya", "alkh sir"]
})

pd.concat([df1, df2], ignore_index=True)
pd.concat([df1, df2], axis=1)

   id   Name  id          Name
0   1  tanya   4  Shradha didi
1   2  sahil   5   Aman Bhaiya
2   3  kirti   6      alkh sir